site_name: KOSMOS
repo_url: https://github.com/konkarlab/KOSMOS
edit_uri: -/edit/main/docs/

nav:
    - Introduction: introduction_fr.md
    - I/ Sourcer: sourcing_fr.md
    - II/ Fabrication :
        - 1. Matériel nécèssaire: tools_fr.md
        - 2. Fabrications des piéces: productions_of_parts_fr.md
        - 3. Guide d'assemblage: assembly-guide_fr.md
        - 4. Installation du software: software_install_fr.md
        - 5. Etalonnage du temps de pause: calibrate_fr.md
        - Annexes:
          - Fabrication d'un PCB: make_a_PCB_fr.md 
          - Commander un PCB à un prestataire spécialisé: pcb_ordering.md
          - Upgrader au mode programmable: micado_upgrade_fr.md

    - III/ Usage en mer :
        - 1. Check-list: check-list_fr.md
        #- 2. Guide de déploiement: deployment.md
        #- 3. Retour à terre: landing.md
    
    - IV/ Collecte et gestion des données :
        - 3. Collecte des images: collecting_pictures_fr.md
        - 2. Correction des images: image-processing_fr.md
    
    - V/ Modifier / Contribuer : 
        - 1. Editer cette documentation: edit-this-doc_fr.md
        - 2. Détails des fichiers 3D modifiables: modify_3Dmodels.md
        
    - A propos :
        - Licence : license.md
        
theme:
    name: material
    palette:
      primary: blue

plugins:
  - search

markdown_extensions:
    - smarty
    - sane_lists
    - admonition
    - toc:
        permalink: true

